---
version: 2

updates:
  - package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    directory: '/'
    schedule: {interval: weekly, day: 'monday', time: '05:00', timezone: Europe/Prague}
    open-pull-requests-limit: 0 # Only security updates
    groups:
      pip-security-updates:
        applies-to: security-updates
        update-types: [minor, patch]
      pip-version-updates:
        applies-to: version-updates
        update-types: [minor]
    commit-message: {prefix: 'ci(deps-pip): [skip ci]'}
    reviewers: ['tomassebestik']
    labels: ['dependencies', 'Status: Reviewing']
    pull-request-branch-name: {separator: '-'}
    ignore:
      - dependency-name: '*'
        versions: ['*']

  - package-ecosystem: github-actions
    directory: '/'
    schedule: {interval: weekly, day: 'monday', time: '05:00', timezone: Europe/Prague}
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        update-types: [minor, patch] # Group minor and patch updates (for major create separate PR
      github-actions-version-updates:
        applies-to: version-updates
        update-types: [minor, patch] # Group minor and patch updates (for major create separate PR
    commit-message: {prefix: 'ci(dependabot-ci): [skip ci]'}
    reviewers: ['tomassebestik']
    labels: ['dependencies', 'Status: Reviewing']
    pull-request-branch-name: {separator: '-'}
    ignore:
      - dependency-name: '*'
        versions: ['*']
